#!/usr/bin/env python3
"""Generate the dependency-free PrintSphere launcher bitmap.

SPDX-License-Identifier: MIT
"""

from pathlib import Path


SIZE = 200
BLACK = (0, 0, 0)
PANEL = (7, 17, 15)
RING = (21, 53, 45)
ACCENT = (32, 201, 151)
WHITE = (223, 252, 244)


def inside_circle(x, y, cx, cy, radius):
    return (x - cx) ** 2 + (y - cy) ** 2 <= radius**2


def near_segment(x, y, x1, y1, x2, y2, width):
    vx, vy = x2 - x1, y2 - y1
    wx, wy = x - x1, y - y1
    length_sq = vx * vx + vy * vy
    t = 0 if length_sq == 0 else max(0, min(1, (wx * vx + wy * vy) / length_sq))
    px, py = x1 + t * vx, y1 + t * vy
    return (x - px) ** 2 + (y - py) ** 2 <= (width / 2) ** 2


def pixel(x, y):
    color = BLACK
    if inside_circle(x, y, 100, 100, 76):
        color = RING
    if inside_circle(x, y, 100, 100, 69):
        color = PANEL

    segments = [
        (60, 53, 140, 53, 9, ACCENT),
        (60, 53, 60, 132, 9, ACCENT),
        (140, 53, 140, 132, 9, ACCENT),
        (60, 132, 140, 132, 9, ACCENT),
        (73, 71, 127, 71, 8, WHITE),
        (100, 71, 100, 91, 8, WHITE),
        (88, 91, 112, 91, 8, WHITE),
        (88, 91, 95, 105, 8, WHITE),
        (112, 91, 105, 105, 8, WHITE),
        (76, 119, 124, 119, 9, ACCENT),
        (70, 146, 130, 146, 9, ACCENT),
    ]
    for x1, y1, x2, y2, width, stroke in segments:
        if near_segment(x, y, x1, y1, x2, y2, width):
            color = stroke
    if inside_circle(x, y, 100, 105, 5):
        color = WHITE
    return color


def rgb565_bytes():
    data = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b = pixel(x + 0.5, y + 0.5)
            value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            data.extend((value & 0xFF, value >> 8))
    return data


def main():
    data = rgb565_bytes()
    lines = [
        "/* Generated by firmware/tools/gen_printsphere_icon.py. */",
        "/* SPDX-License-Identifier: MIT */",
        "#include <lvgl.h>",
        "",
        "const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t icon_printsphere_map[] = {",
    ]
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    lines.extend(
        [
            "};",
            "",
            "const lv_image_dsc_t icon_printsphere = {",
            "    .header.cf = LV_COLOR_FORMAT_RGB565,",
            "    .header.magic = LV_IMAGE_HEADER_MAGIC,",
            f"    .header.w = {SIZE},",
            f"    .header.h = {SIZE},",
            f"    .data_size = {SIZE * SIZE} * 2,",
            "    .data = icon_printsphere_map,",
            "};",
            "",
        ]
    )
    output = Path(__file__).resolve().parents[1] / "assets" / "icon_printsphere.c"
    output.write_text("\n".join(lines))
    print(f"generated {output} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
